language: ruby
rvm:
  - 2.5.1
before_script:
  - psql -c 'create database Soundwave_test;' -U postgres
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec
services:
  - postgresql
